window.App.ActionTypes = {
  LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',
  CREATE_TODO: 'CREATE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  SHOW_ALL_TODO: 'SHOW_ALL_TODO',
  SHOW_ACTIVE_TODO: 'SHOW_ACTIVE_TODO',
  SHOW_COMPLETED_TODO: 'SHOW_COMPLETED_TODO',
  CLEAR_COMPLETED_TODO: 'CLEAR_COMPLETED_TODO'
};
