window.App.ActionTypes = {
  LOAD_TODOS_SUCCESS: 'LOAD_TODOS_SUCCESS',
  CREATE_TODO: 'CREATE_TODO',
  UPDATE_TODO: 'UPDATE_TODO',
  TOGGLE_TODO: 'TOGGLE_TODO',
  DELETE_TODO: 'DELETE_TODO',
  SWITCH_SHOW_TODO: 'SWITCH_SHOW_TODO',
  CLEAR_COMPLETED_TODO: 'CLEAR_COMPLETED_TODO',
  COMPLETED_ALL_TODO: 'COMPLETED_ALL_TODO'
};
